### ISSUE TITLE
Search doesn't seem to work

### ISSUE THREAD

**Issue by jcuenod** [BibleJS/bible.js#8]
Maybe I'm doing something wrong:

    $ bible --s "God"
    Results for search: God
    Error:  Module don't support search method

**Comment by IonicaBizau** [comment]
Hey @jcuenod!

Yes, the [`bible-english`](https://github.com/BibleJS/bible-english) submodule doesn't *currently* support searching. For that we should add a search method (https://github.com/BibleJS/bible-english/issues/3) which will use the remote APIs.

We can move the discussion there since this issue is not related to this library but to a submodule.

**Comment by IonicaBizau** [comment]
And, of course, contributions are welcome! :sparkles:
